# Data Cleaning and Preparation in Pandas

In [3]:
import pandas as pd
string_data = pd.Series(['aardvark', 'artichoke', 'np.nan', 'avocado'])

string_data

0     aardvark
1    artichoke
2       np.nan
3      avocado
dtype: object

In [5]:
string_data.isnull()

0    False
1    False
2    False
3    False
dtype: bool

In [6]:
string_data[0] = None

string_data.isnull()

0     True
1    False
2    False
3    False
dtype: bool

In [7]:
from numpy import nan as NA

data = pd.Series([1, NA, 3.5, NA, 7])

data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [8]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                    [NA, NA, NA], [NA, 6.5, 3.]])

cleaned = data.dropna()

data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [11]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [12]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [13]:
data[4] = NA

data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [14]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
import numpy as np

df = pd.DataFrame(np.random.randn(7, 3))

df.iloc[:4, 1] = NA

df.iloc[:2, 2] = NA

df

0         1         2
0  0.997937       NaN       NaN
1  0.976603       NaN       NaN
2 -0.211720       NaN  0.617643
3  0.812121       NaN -0.598569
4  0.445804  0.279080 -0.624773
5  0.331046 -1.579563  1.271863
6  2.581614  1.055151  1.930305

In [17]:
df.dropna()

0         1         2
4  0.445804  0.279080 -0.624773
5  0.331046 -1.579563  1.271863
6  2.581614  1.055151  1.930305

In [18]:
df.dropna(thresh=2)

0         1         2
2 -0.211720       NaN  0.617643
3  0.812121       NaN -0.598569
4  0.445804  0.279080 -0.624773
5  0.331046 -1.579563  1.271863
6  2.581614  1.055151  1.930305

In [19]:
df.fillna(0)

0         1         2
0  0.997937  0.000000  0.000000
1  0.976603  0.000000  0.000000
2 -0.211720  0.000000  0.617643
3  0.812121  0.000000 -0.598569
4  0.445804  0.279080 -0.624773
5  0.331046 -1.579563  1.271863
6  2.581614  1.055151  1.930305

In [20]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.997937  0.500000  0.000000
1  0.976603  0.500000  0.000000
2 -0.211720  0.500000  0.617643
3  0.812121  0.500000 -0.598569
4  0.445804  0.279080 -0.624773
5  0.331046 -1.579563  1.271863
6  2.581614  1.055151  1.930305

In [21]:
_ = df.fillna(0, inplace=True)

df

0         1         2
0  0.997937  0.000000  0.000000
1  0.976603  0.000000  0.000000
2 -0.211720  0.000000  0.617643
3  0.812121  0.000000 -0.598569
4  0.445804  0.279080 -0.624773
5  0.331046 -1.579563  1.271863
6  2.581614  1.055151  1.930305

In [22]:
df = pd.DataFrame(np.random.randn(6, 3))

df.iloc[2:, 1] = NA

df.iloc[4:, 2] = NA

df 

0         1         2
0 -0.186788  0.382909 -0.336185
1 -0.135482 -1.953899  0.249566
2  0.127064       NaN -1.605451
3 -0.872162       NaN -0.762988
4 -0.504234       NaN       NaN
5  1.322096       NaN       NaN

In [25]:
df.fillna(method='ffill')

/var/folders/n6/_1rxv4ns7672lxq4v_lfp9mc0000gn/T/ipykernel_69105/1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')


0         1         2
0 -0.186788  0.382909 -0.336185
1 -0.135482 -1.953899  0.249566
2  0.127064 -1.953899 -1.605451
3 -0.872162 -1.953899 -0.762988
4 -0.504234 -1.953899 -0.762988
5  1.322096 -1.953899 -0.762988

In [26]:
df.fillna(method='ffill', limit=2)

/var/folders/n6/_1rxv4ns7672lxq4v_lfp9mc0000gn/T/ipykernel_69105/2719175769.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=2)


0         1         2
0 -0.186788  0.382909 -0.336185
1 -0.135482 -1.953899  0.249566
2  0.127064 -1.953899 -1.605451
3 -0.872162 -1.953899 -0.762988
4 -0.504234       NaN -0.762988
5  1.322096       NaN -0.762988

In [27]:
data = pd.Series([1., NA, 3.5, NA, 7])

data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [38]:
import pandas as pd

data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})

data


k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [39]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [40]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [41]:
data['v1'] = range(7)
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [42]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [44]:
import pandas as pd

data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

print(data)


          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0


In [45]:
lowercased = data['food'].str.lower()

lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [46]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [47]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [48]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [49]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [50]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [52]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

transform = lambda x: x[:4].upper()

data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [53]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [54]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [56]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [57]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

bins = [18, 25, 35, 60, 100]

cats = pd.cut(ages, bins)

cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [58]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [59]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [60]:
pd.value_counts(cats)

/var/folders/n6/_1rxv4ns7672lxq4v_lfp9mc0000gn/T/ipykernel_69105/1485279302.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(cats)


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [61]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [62]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [63]:
data = np.random.rand(20)
pd.cut(data, 4, precision=2)

[(0.23, 0.45], (0.23, 0.45], (0.68, 0.91], (0.00054, 0.23], (0.00054, 0.23], ..., (0.45, 0.68], (0.68, 0.91], (0.23, 0.45], (0.00054, 0.23], (0.23, 0.45]]
Length: 20
Categories (4, interval[float64, right]): [(0.00054, 0.23] < (0.23, 0.45] < (0.45, 0.68] < (0.68, 0.91]]

In [65]:
data = np.random.randn(20)

cats = pd.qcut(data, 4)

data

array([ 0.04243765,  1.26107692,  0.81886025,  0.96690433,  1.5515046 ,
       -0.10146582,  0.81748573, -0.55840951,  0.08904246, -0.41581732,
       -1.11228327, -1.30373512, -1.46553033,  0.48049905, -1.50169295,
        0.16796127, -1.32678273, -0.59656176, -0.27945919,  0.31447948])

In [66]:
pd.value_counts(cats)

/var/folders/n6/_1rxv4ns7672lxq4v_lfp9mc0000gn/T/ipykernel_69105/1485279302.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(cats)


(-1.503, -0.725]     5
(-0.725, -0.0295]    5
(-0.0295, 0.565]     5
(0.565, 1.552]       5
Name: count, dtype: int64

In [67]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-0.0295, 0.996], (0.996, 1.552], (-0.0295, 0.996], (-0.0295, 0.996], (0.996, 1.552], ..., (-0.0295, 0.996], (-1.341, -0.0295], (-1.341, -0.0295], (-1.341, -0.0295], (-0.0295, 0.996]]
Length: 20
Categories (4, interval[float64, right]): [(-1.503, -1.341] < (-1.341, -0.0295] < (-0.0295, 0.996] < (0.996, 1.552]]

In [68]:
data = pd.DataFrame(np.random.randn(1000, 4))

data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.018394    -0.035235    -0.047352    -0.033984
std       0.959802     1.006464     1.020466     1.006822
min      -4.183434    -2.940167    -3.493102    -2.981620
25%      -0.653990    -0.731572    -0.717144    -0.726019
50%       0.014482    -0.025743    -0.095922    -0.018926
75%       0.648040     0.654888     0.644994     0.636362
max       2.986280     3.289474     3.227609     2.906036

In [69]:
col = data[2]

col[np.abs(col) > 3]

146   -3.277378
212   -3.307152
349   -3.493102
468   -3.012240
525    3.227609
Name: 2, dtype: float64

In [74]:
data[(np.abs(data) > 3).any(axis=1)]

0         1         2         3
33  -1.230947  3.289474 -0.303370 -0.142056
146  0.495594  0.578090 -3.277378  1.254537
212  0.015540  1.912876 -3.307152 -0.010554
349 -1.116967 -0.527631 -3.493102  0.605286
468  0.538728  0.060136 -3.012240 -1.943537
525 -0.350449  1.794099  3.227609  0.981993
826 -4.183434  1.325515  1.784334  2.535752

In [75]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.019577    -0.035524    -0.046489    -0.033984
std       0.955335     1.005548     1.016392     1.006822
min      -3.000000    -2.940167    -3.000000    -2.981620
25%      -0.653990    -0.731572    -0.717144    -0.726019
50%       0.014482    -0.025743    -0.095922    -0.018926
75%       0.648040     0.654888     0.644994     0.636362
max       2.986280     3.000000     3.000000     2.906036

In [76]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0  1.0 -1.0
1  1.0  1.0 -1.0  1.0
2  1.0  1.0  1.0  1.0
3 -1.0 -1.0 -1.0  1.0
4 -1.0 -1.0  1.0 -1.0

In [79]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

sampler = np.random.permutation(5)

sampler


array([0, 4, 3, 2, 1])

In [80]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [81]:
df.take(sampler)

0   1   2   3
0   0   1   2   3
4  16  17  18  19
3  12  13  14  15
2   8   9  10  11
1   4   5   6   7

In [82]:
df.sample(n=3)

0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [83]:
choices = pd.Series([5, 7, -1, 6, 4])

draws = choices.sample(n=10, replace=True)

draws

3    6
3    6
2   -1
3    6
4    4
1    7
3    6
0    5
4    4
3    6
dtype: int64

In [84]:
df = pd.DataFrame({'key': ['a', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})

pd.get_dummies(df['key'])

a      b      c
0   True  False  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [86]:
dummies = pd.get_dummies(df['key'], prefix='key')

df_with_dummy = df[['data1']].join(dummies)

df_with_dummy

data1  key_a  key_b  key_c
0      0   True  False  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [87]:
np.random.seed(12345)
values = np.random.rand(10)

values 

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [88]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [89]:
val = 'a,b, guido'

val.split(',')

['a', 'b', ' guido']

In [90]:
pieces = [x.strip() for x in val.split(',')]

pieces

['a', 'b', 'guido']

In [91]:
first, second, third = pieces

first + '::' + second + '::' + third

'a::b::guido'

In [92]:
'::'.join(pieces)

'a::b::guido'

In [93]:
'guido' in val 

True

In [94]:
val.index(',')

1

In [95]:
val.find(':')

-1

In [97]:
val.count(',')

2

In [98]:
val.replace(',', '::')

'a::b:: guido'

In [99]:
val.replace(',', '')

'ab guido'

In [101]:
import re

text = "foo bar\t baz  \tqux"

re.split('\\s+', text)

['foo', 'bar', 'baz', 'qux']

In [104]:
regex = re.compile('\\s+')

regex.findall(text)

[' ', '\t ', '  \t']

In [105]:
regex.findall(text)

[' ', '\t ', '  \t']

In [106]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

regex.findall(text)

[' ', '\n', ' ', '\n', ' ', '\n', ' ', '\n']

In [107]:
m = regex.search(text)

m

<re.Match object; span=(4, 5), match=' '>

In [108]:
text[m.start():m.end()]

' '

In [109]:
print(regex.match(text))

None


In [111]:
print(regex.sub('REDACTED', text))

DaveREDACTEDdave@google.comREDACTEDSteveREDACTEDsteve@gmail.comREDACTEDRobREDACTEDrob@gmail.comREDACTEDRyanREDACTEDryan@yahoo.comREDACTED


In [113]:
import re

# 修正正则表达式
pattern = r'([A-Za-z0-9._%+-]+)@([A-Za-z0-9.-]+)\.([A-Za-z]{2,4})'

# 编译正则表达式
regex = re.compile(pattern, flags=re.IGNORECASE)

# 匹配测试字符串
m = regex.match('wesm@bright.net')

# 获取匹配的分组
if m:
    print(m.groups())
else:
    print("No match found")


('wesm', 'bright', 'net')


In [114]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [115]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



In [116]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com', 'Wes': np.nan}

data = pd.Series(data)

data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [117]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [118]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [119]:
pattern

'([A-Za-z0-9._%+-]+)@([A-Za-z0-9.-]+)\\.([A-Za-z]{2,4})'

In [120]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [121]:
matches = data.str.match(pattern, flags=re.IGNORECASE)

matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [130]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object